title: Dept.
description: >- # this means to ignore newlines until "baseurl:"
  Describing the Present Tense
collections:
  posts:
    title: Posts
    output: true
  workshops:
    title: Workshops
    output: true
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dept.today" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
